name: CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'src/**/*'
      - 'tests/**/*'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - 'src/**/*'
      - 'tests/**/*'
      - '.github/workflows/*.yml'
jobs:
  test:
    strategy:
      matrix:
        os:
          - macOS-14
          - macOS-15
    uses: YOCKOW/SSTest/.github/workflows/reusable-SSTest.yml@main
    with:
      os: ${{ matrix.os }}
