#!/bin/zsh

################################################################################
# fontutil-tests/finalize
#   © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
################################################################################

set -eu
