#!/bin/zsh

################################################################################
# fontutil-tests/test-family
#   © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
################################################################################

set -eu

local -r -A fontList=(
  [otf/Mplus1-Medium.otf]="M PLUS 1 Medium"
  [otf/Mplus2-ExtraBold.otf]="M PLUS 2 ExtraBold"
  [ttf/Mplus1-Regular.ttf]="M PLUS 1"
  [ttf/MplusCodeLatin50-ExtraLight.ttf]="M PLUS Code Latin 50 ExtraLight"
)
local fontFile
for fontFile in ${(k)fontList}; do
  local expectedFamilyName="${fontList[$fontFile]}"
  local fontFilePath="$FONTUTIL_TEST_FONTS_DIR/$fontFile"
  if [[ ! -f "$fontFilePath" ]]; then
    SSTFail "Font file not found: $fontFilePath" -l ${(%):-%I}
    continue
  fi

  local familyName=$("$FONTUTIL_COMMAND" family "$fontFilePath")
  SSTAssertStringEqual "$familyName" "$expectedFamilyName" -l ${(%):-%I}
done
