#!/bin/zsh

################################################################################
# fontutil-tests/test-copyright
#   © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
################################################################################

set -eu

local -r -A fontList=(
  [otf/Mplus1-Medium.otf]="Copyright 2021 The M+ FONTS Project Authors (https://github.com/coz-m/MPLUS_FONTS)"
  [ttf/Mplus1-Regular.ttf]="Copyright 2021 The M+ FONTS Project Authors (https://github.com/coz-m/MPLUS_FONTS)"
)
local fontFile
for fontFile in ${(k)fontList}; do
  local expectedFamilyName="${fontList[$fontFile]}"
  local fontFilePath="$FONTUTIL_TEST_FONTS_DIR/$fontFile"
  if [[ ! -f "$fontFilePath" ]]; then
    SSTFail "Font file not found: $fontFilePath" -l ${(%):-%I}
    continue
  fi

  local familyName=$("$FONTUTIL_COMMAND" copyright "$fontFilePath")
  SSTAssertStringEqual "$familyName" "$expectedFamilyName" -l ${(%):-%I}
done
