#!/bin/zsh

################################################################################
# fontutil-tests/test-postscript-name
#   © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
################################################################################

set -eu

local -r -A fontList=(
  [otf/Mplus2-Thin.otf]="MPLUS2-Thin"
  [ttf/MplusCodeLatin50-Medium.ttf]="MPLUSCodeLatin50-Medium"
)
local fontFile
for fontFile in ${(k)fontList}; do
  local expectedFondName="${fontList[$fontFile]}"
  local fontFilePath="$FONTUTIL_TEST_FONTS_DIR/$fontFile"
  if [[ ! -f "$fontFilePath" ]]; then
    SSTFail "Font file not found: $fontFilePath" -l ${(%):-%I}
    continue
  fi

  local fondName=$("$FONTUTIL_COMMAND" postscript-name "$fontFilePath")
  SSTAssertStringEqual "$fondName" "$expectedFondName" -l ${(%):-%I}
done
