#!/bin/zsh

################################################################################
# fontutil-tests/test-authors
#   © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
################################################################################

set -eu

local -r -A fontList=(
  [otf/Mplus1-Medium.otf]="Coji Morishita"
  [ttf/Mplus1-Regular.ttf]="Coji Morishita"
)
local fontFile
for fontFile in ${(k)fontList}; do
  local expectedFamilyName="${fontList[$fontFile]}"
  local fontFilePath="$FONTUTIL_TEST_FONTS_DIR/$fontFile"
  if [[ ! -f "$fontFilePath" ]]; then
    SSTFail "Font file not found: $fontFilePath" -l ${(%):-%I}
    continue
  fi

  local familyName=$("$FONTUTIL_COMMAND" authors "$fontFilePath")
  SSTAssertStringEqual "$familyName" "$expectedFamilyName" -l ${(%):-%I}
done
