#!/bin/zsh

################################################################################
# fontutil-tests/test-fond-name
#   © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
################################################################################

set -eu

local -r -A fontList=(
  [otf/Mplus2-Medium.otf]="MPLUS2-Medium"
  [ttf/Mplus1-Medium.ttf]="MPLUS1-Medium"
)
local fontFile
for fontFile in ${(k)fontList}; do
  local expectedFondName="${fontList[$fontFile]}"
  local fontFilePath="$FONTUTIL_TEST_FONTS_DIR/$fontFile"
  if [[ ! -f "$fontFilePath" ]]; then
    SSTFail "Font file not found: $fontFilePath" -l ${(%):-%I}
    continue
  fi

  local fondName=$("$FONTUTIL_COMMAND" fond-name "$fontFilePath")
  SSTAssertStringEqual "$fondName" "$expectedFondName" -l ${(%):-%I}
done
